- folding/__init__.py
- folding/base/neuron.py
weight setting was turned off (oops). Turn this back on so that validators can actually work!
> add weight setting into validation schema

- folding/miners/folding_miner.py
- folding/utils/config.py
- folding/validators/protein.py
- neurons/validator.py
This PR ensures that we do not preferentially add files to the `md_inputs`, but rather do it each time we call the protein class from the `from_job` method. This is to enable miners to start a simulation even if they miss the first submission.
> md_inputs is sent on each forward query

- folding/base/miner.py
- folding/base/neuron.py
- folding/miners/folding_miner.py
- folding/utils/ops.py
Miners currently try and set weights, and this is because many of the miners on the network have validator permits (early days without many valis with high stake on the network). Because of this, it can cause miners to die and have to restart in pm2, causing child processes not to die properly. Therefore, we add this as a method to `pass` . 
we also add better logging through a `get_tracebacks` function now in `folding/ops`. 
Miner step is now only increased when the forward method is called (ie, only when they receive queries from validators)
> Fix miner weighting, and logging

- folding/miners/folding_miner.py
Miners will keep jobs alive for way longer than needed if validators don't query properly. Make miners more efficient by always checking what jobs have finished on ANY validator query.
> change miner to remove jobs that have already finished without validator

- install.sh
This PR enhances the GROMACS build script to dynamically determine the number of physical CPU cores on the system and use this value for the make -j command. This ensures optimal utilization of system resources across different machines without manual adjustment.
> Improve Makefile to Dynamically Determine Number of Physical Cores

- folding/store.py
- folding/validators/forward.py
- folding/validators/protein.py
- neurons/validator.py
With insights into the data that we've been receiving after the latest update we felt it was needed to finally change epsilon from a simple static number into a variable that actually adapts based on the job. 
After some analysis we found a clear trend between the average change in loss (energy) per miner update and the amount of total atoms in the protein as seen on the following graph:
Note that both axes are in log scale due to the disparity in scale of the data. It is clear that the changes in loss we observe are increasing with the size of the protein. There is a few reasons we can't simply use the trendline seen in the image to model as epsilon:
1. The data we currently possess is extremely noisy due to the instability of the network and hence the standard deviation of the dataset …
> Made epsilon change in relation to the protein complexity

- folding/rewards/reward_pipeline.py
- neurons/validator.py
- tests/test_linear_decreasing_reward.py
This PR includes a slightly different formulation of the reward stack. Miners that are competing with no one else, they get 100% of the reward. If the top miner stops replying and no one else is competing, they still get 100% of the reward. Anyone else that starts to compete will start to obtain some reward.
> change miner rewards

- folding/validators/protein.py
In relation to reports such as [this](https://discord.com/channels/799672011265015819/1234881153832321024/1288791456391106645)
When init_energy is nan it then gets saved in the job store and saved into a csv and when we eval it, it won't be recognized Staging
> fix eval nan bug

- folding/store.py
- folding/validators/forward.py
- folding/validators/protein.py
- neurons/validator.py
This is to catch edge cases such as the MUV error, this will make it so that validators will not restart on such errors
> Added logic that if from_job fails we stop the job and continue

- folding/validators/forward.py
Our base miner only sets its own seed when the system config does not have their own seed. We were always passing a seed to the system_config so all miners ran the same seed. This is not the intention as we don't want to run deterministic jobs. each miner gets to set their own seed nowStaging
> Removed the seed from the JobSubmissionSynapse

- folding/store.py
Due to a bug in the percent improvement calculations, when a lower energy was submitted percent improvement was always negative. 
We also change the logical flow of the if-statements to make is more clear to the reader
> Fixed a bug in best loss calculations

- folding/miners/folding_miner.py
If the validator sends a None seed, miner must set and cascade their own seed into the the system
> Fix miner seeding

- folding/utils/config.py
- folding/utils/logging.py
Since we changed the way we log on wandb, we don't save cohesive log files into wandb. This PR saves terminal logs into the wandb run as a file
> started saving logging files to wandb

- folding/validators/protein.py
- folding/validators/reward.py
1. Exploit where miners could get through gradient detection by modifying miner logs, we're now basing gradient detection on `check_energy` which is generated by the validator. Example: https://wandb.ai/macrocosmos/folding-openmm/runs/pyb46ll1/overview. Miner number 9 has a miner log that looks like this: 
2. There is an exploit where miners get lower energies in their checkpoints without causing a gradient in check_energy. An example: https://wandb.ai/macrocosmos/folding-openmm/runs/g3019uur/overview some energies are way lower than any energy observed in `miner_energy` or `checked_energy`
Thank you to our valued community members for elucidating these issues to us! Thank you Kumiho, Loayei, BC | Tensorized, OzLancer
> Exploit fixes

- folding/base/validator.py
- folding/experiments/sensitivity_analysis.py
- folding/organic/validator.py
- folding/protocol.py
- folding/utils/config.py
- folding/validators/forward.py
- neurons/validator.py
- tests/test_simulation_executor.py
- tests/test_template_validator.py
Add attribute `best_submitted_energy` to the `JobSubmissionSynapse` so miners can use this to compare their loss to the best recorded.
> return best miner energy for the job so miners can compare

- README.md
conda create requires python=<version> not python<version>
> fixed typo in README.md for conda create 

- folding/validators/protein.py
`checked_energy` is the same value for every simulation step, basically mitigating our reproducibility. Meaning miners can modify simulations however they want without us finding out.
* Set step size to 0 to freeze the simulation ❌ 
* Set temperature to 0 ❌ 
* Make all velocities 0 ❌ 
* Create a custom integrator that makes all velocities 0 at every simulation step ❌ 
* Added a custom external force that adds the exact opposite of the velocity of each particle ❌ 
* Add a custom external force that will restrain all atoms ❌
> Fix for exploit where miner can affect the reproduced sim

- folding/store.py
- neurons/validator.py
EMA is weird and order _really_ matters and updating one at a time _really_ matters. 
Some things to improve here:
This should be fine, but it would be great to confirm that all validators see the same weights at the same time in the same order. If not, then their weights are going to be inconsistent
> add background task for updating uids for rewards on inactive jobs

- folding/rewards/linear_reward.py
Replaces the linearly decreasing function. The new function assigns values to every element (no 0s) This means miners will always receive reward if they are in the top 5.
Mathematical definition of the new function:
$$a_i = A \cdot \frac{2(n-i)}{n(n+1)}$$
where 
* $A$ is the amount to distribute
* $n$ is the number of elements
* $i$ is the index (0 to $n$-1)
> refactor linear_reward.py to use weighted distribution for rewards

- folding/base/simulation.py
- folding/registries/evaluation_registry.py
- folding/utils/ops.py
- folding/validators/protein.py
- folding/validators/reward.py
include initialize_with_solvent which includes solvent during initial simulation creation. Adding the solvent is a non-deterministic process that should only be done once, at the time of simulation creation from the validator. All reloading of the simulation should be done using the pdb _after_ solvent was added. 
At times, we have seen the pdb grow to as much as 300x larger compared to the original, non-solvent counterpart.
> Fix solvent

- folding/base/miner.py
- folding/miners/folding_miner.py
- folding/protocol.py
- folding/utils/uids.py
- folding/validators/forward.py
- neurons/validator.py
There is a dynamic that has emerged within Folding where miners can turn off their participation once they have gotten near the top of the incentive curve because we do not negatively impact them for not participating. Therefore, we now query _all_ miners when a job's `time to live` parameter is up. 
The PR: 
1. removes the `ParticipationSynapse` from the system entirely
2. removes some old, unused code
> remove idea of a participation synapse

- folding/base/validator.py
- folding/utils/config.py
- folding/validators/reward.py
Validators are having a hard time to come to proper vtrust. This I due to two major reasons: 
1. There is a lot of noise / instability in the reward distributions because there are so many uids in the rewards calculation, and
2. Validators set weights at different times, so it could be that they are seeing slightly different windows of the rewards even though long term they have the right convergence. 
The first image below shows all the miner uids in the network and their relative performance. As you can see, there is a lot of variance in scoring. 
We implement a new idea, an asymmetric reward function where you increase reward at the same rate, but lose reward at a lower rate, with `alpha = 0.03`, making the rate of loss `0.10/0.03 = 3.33x slower`. This is done via: 
```python …
```
> Asymmetric Weight Scoring

- folding/registries/miner_registry.py
- folding/validators/reward.py
When wandb is turned on, the valuator fails to get json serialized:
```
0|sn25_validator  | 2025-04-18 08:15:30.651 | SUCCESS | updated a wandb run
0|sn25_validator  | 2025-04-18 08:15:30.656 | ERROR | Error in update_jobs: Traceback (most recent call last):
0|sn25_validator  |   File "/root/folding/neurons/validator.py", line 636, in update_jobs
0|sn25_validator  |     await self.update_job(job=job)
0|sn25_validator  |   File "/root/folding/neurons/validator.py", line 478, in update_job
0|sn25_validator  |     log_event(
0|sn25_validator  |   File "/root/folding/folding/utils/logging.py", line 130, in log_event
0|sn25_validator  |     run.log(event)
0|sn25_validator  |   File "/root/miniconda3/envs/folding/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper …
```
> Refactor miner evaluation logic to remove evaluator from initial logs

- folding/miners/folding_miner.py
- folding/registries/evaluation_registry.py
- folding/utils/opemm_simulation_config.py
- neurons/validator.py
- Made trajectories mandatory
- changed number_of_checkpoints calculation to be based off of final checkpoint step
- instead of using checkpoint step to determine the right log file section in is_checkpoint_valid we precalculate what the checkpoint should be based on our save interval
- added trajectory validation by reproducing trajectories and checking the RMSD of each frame between the miner trajectories and the checked trajectories
- Used saving intervals from the system configs in base miner
> Refactor validation process to include trajectories

- folding/registries/miner_registry.py
- Renamed `add_miner_to_registry` to `_add_miner_to_registry` to indicate it is a private method.
- Updated references to the renamed method throughout the class for consistency.
- Ensured miner logs are initialized correctly when retrieving all miner logs.
> Ensured miner logs are initialized correctly 
