macrocosm-os/mainframe

- folding/base/validator.py
- folding/miners/folding_miner.py
- folding/store.py
- folding/utils/ops.py
- folding/validators/forward.py
- folding/validators/protein.py
- neurons/miner.py
- neurons/validator.py
This PR adds a bunch of important functionality, but it is larger than it needs to be since I blacked some of it :) 
1. Adds logic to see if we should change the job to `inactive` if we get back all 0 energies 
2. Agnostically search for `topol` and `posre` files using `glob`. This allows us to catch any edge case-chains we might not have been sending in the past. Not doing this was causing miners to fail 
3. Change the way we set the `created_at` and `updated_at` parameters, as these did not change in the original implementation 
4. Changing many of the `bt.logging.success` to `bt.logging.debug`
5. fixes energy checking. Before it was `torch.all(energies) ==0`, now is `(energies == 0).all()`
> Major Bug Fixes

- folding/miners/folding_miner.py
Miners are unstable, and previous solutions for solving improper miner weighting did not solve it. With the help of the community, we have found two highly probable causes for the instabilities: 
1. Miners were computing intermediate `.gro` files before sending data to the validator. This was to ensure that this command could run when the validator does it, but it was causing file read/write problems that would lead to SIGKILLS
2. `.trr` files that are created during simulation can become _massive_. Right now, the implementation of Folding does NOT need this file. When this was attached to the synapse, we would get comms issues leading to miners restarting. Since the bittensor middleware is not suited for such things, we remove it from the synapse. 
In regards to filesize, we are talking …
> remove intermediate gro calculations, and dont send trr

- folding/__init__.py
This version will be used to re-synchronize the validators with enhanced logging capabilities. We will use the data created by the subsequent runs to troubleshoot remaining issues and resolve network instabilities.
> Version 0.0.2

- folding/miners/folding_miner.py
- folding/utils/ops.py
adds wandb logging to miners so that we can have additional flexibility
> add wandb logging to minerside analysis

- folding/miners/folding_miner.py
this remove the timeout checking on staging, as it is not functional. This is a PR to be easier to track
> remove timeout deletion since there is an issue with multi processes

- folding/rewards/linear_reward.py
- neurons/validator.py
- tests/test_linear_decreasing_reward.py
This PR incorporates the following algorithm into the reward stack:
> add a linearly decreasing reward schema

- neurons/validator.py
generic check to see if a hotkey exists on the metagraph. Some hotkeys seem to not exist after the job was created. Jobs are long and this can periodically happen
> get uids but check if they are registered on the metagraph

- folding/utils/logging.py
- neurons/validator.py
> Restart the wandb run every 24 hours

- folding/utils/openmm_forcefields.py
- folding/validators/forward.py
- folding/validators/hyperparameters.py
New `OpenMMRegistry` with classes that correspond to this, along with some reformatting of the Hyperparameter sampling to accommodate this new format. 
Python Black. 
WARNING: Untested
> Hyperparameter Sampling + Registry

- environment.yml
- folding/miners/folding_miner.py
- folding/protocol.py
- folding/validators/forward.py
- folding/validators/protein.py
- install.sh
- setup.py
This PR improves the protein class forward method and attaches a new attribute to the synapse
> Improve Synapse + Install

- folding/utils/logging.py
- neurons/validator.py
This PR adds molecule visualization to wandb
> wandb Molecule logging

- folding/base/simulation.py
- folding/miners/folding_miner.py
- folding/protocol.py
- folding/utils/opemm_simulation_config.py
Move simulations steps into the system config to hold everything together, and make it modular for the vali
> move simulation steps into the system config

- folding/base/simulation.py
- folding/miners/folding_miner.py
> Fix type hints

- folding/utils/ops.py
- folding/validators/protein.py
Added a parameter MIN_STEPS
Added a check for the length of the log file
Added a check to see if the old checkpoint has enough points to continue validation
Checking if the log file has enough points to validate. Ensure that all old checkpoints also have enough steps. This is to ensure that miners cannot exploit the system
> Extra validation steps

- folding/base/neuron.py
- folding/base/validator.py
- folding/utils/ops.py
- Incorporate tenacity into weight setting to try and improve when setting fails
> add tenacity retry to set weights

- pyproject.toml
Add macrocosmos `atom` into the installation
> include atom in install

- folding/base/validator.py
remove the use of torch when interfacing with Bittensor middleware
> fix weight setting from bittensor torch issues

- folding/base/miner.py
- folding/base/neuron.py
- folding/base/simulation.py
- folding/base/validator.py
- folding/experiments/sensitivity_analysis.py
- folding/miners/folding_miner.py
- folding/mock.py
- folding/organic/validator.py
- folding/protocol.py
- folding/rewards/reward_pipeline.py
- folding/utils/config.py
- folding/utils/logger.py
- folding/utils/logging.py
- folding/utils/ops.py
- folding/utils/uids.py
- folding/validators/forward.py
- folding/validators/hyperparameters.py
- folding/validators/protein.py
- folding/validators/reward.py
- neurons/miner.py
- neurons/mock_miner.py
- neurons/validator.py
- scripts/gather_pdbs.py
- tests/test_simulation_executor.py
tested in machine - looks very similar to old logger (could be better with spacing)
> fix-logger

- folding/utils/ops.py
- folding/utils/s3_utils.py
- folding/validators/forward.py
- neurons/validator.py
Change the logic for where the s3 upload happens
> integrate s3 upload into add_job

- folding/store.py
- folding/utils/epistula_utils.py
- scripts/setup_precommit.py
It looked like to me that the updating and uploading of content to the GJP was identical and had only minor logical differences, which in practice shouldn't change due to the if statements that were originally present. Therefore, I factored this out into a different function all together so we can reuse the logic
> move epistula body extraction to utils

- folding/store.py
- folding/utils/s3_utils.py
- folding/validators/reward.py
- neurons/validator.py
Added uploading of the best .cpt file to the global job pool.
* added new s3 function for uploading
* moved around the `update_job` function
* Added new field in `Job`
1 issue is that we can't know the exact .cpt file without passing more variables through the functions
> added uploading of best cpt file to gjp

- folding/utils/epistula_utils.py
Passing the `best_cpt_links` as a list now
> fix best .cpt link upload to gjp

- README.md
Updates to the installation instructions in the `README.md` to include `conda activate folding` after creating the environment, and before running `bash install.sh`
> Update Install Instructions. 

- folding/store.py
- folding/utils/epistula_utils.py
- install.sh
- install_rqlite.sh
- neurons/validator.py
- scripts/setup_precommit.py
- start_read_node.sh
A branch to store all our rqlite integration code. Contains 2 things that we will need regardless:
* rqlite installation
* A script to create a read-node
> Base for RQlite integration

- folding/__init__.py
- pyproject.toml
> version bump 1.4.3

- folding/validators/protein.py
We check if the state reproduce simulation is significantly different (epsilon difference) from the checkpoint reproduced simulation.
> Add state-checkpoint comparison

- folding/validators/protein.py
- neurons/validator.py
1. Increased the threshold of acceptable deviation to 2% between the state file and the checkpoint file
2. Decreased punishment from 0% of rewards to 50%
> lower severity of state-checkpoint check

- documentation/mining.md
> Update mining documentation to clarify Global Job Pool usage and base miner launch 

- neurons/validator.py
Added a check for job creation, if a job is not created in a 12 hour time span the validator will shut down as to indicate that something is wrong
> Add monitoring of job creation

- folding/base/miner.py
- folding/miners/folding_miner.py
- folding/protocol.py
- folding/validators/forward.py
- neurons/validator.py
Reworks the validator and miner in order for all miners to be able to work on all jobs
> Allows for all miners to work on all jobs

- folding/store.py
Since there are uids per job, and if you don't do a job you will be punished, let's make sure that miners have more time to complete.
> increase job times

- folding/organic/organic.py
- folding/store.py
- folding/validators/protein.py
- folding_api/protein.py
- folding_api/queries.py
- folding_api/schemas.py
- folding_api/utils.py
* Passing `time_to_live` to the validator so that the user can specify it
* Added new endpoints to allow the upload of PDB files, reworked Protein pdb handling to allow for this
> Enhancing organic API

- neurons/validator.py
it'll be easier to know what sources have what data if we are able to segment by spec version
> Spec version to s3

- folding_api/main.py
- folding_api/schemas.py
- folding_api/utility_endpoints.py
- folding_api/utils.py
- folding_api/vars.py
- Introduced a new module `utility_endpoints.py` with endpoints for searching PDB IDs and retrieving detailed information about specific PDB structures.
- Added corresponding Pydantic models in `schemas.py` for PDB search responses and detailed PDB information.
- Updated `main.py` to include the new utility router for handling these endpoints.
> Add utility endpoints for PDB search and information retrieval

- folding_api/schemas.py
- folding_api/utility_endpoints.py
- Updated the `JobResponse` model to include `pdb_data` and `final_energy` fields for improved job detail responses.
- Modified the `search_pdb` and `get_job_pool_status` functions to support pagination through `page` and `page_size` parameters, enhancing query flexibility.
- Implemented logic for generating mock miner data when requested, allowing for testing without real data dependencies.
- Improved energy data handling for miners, ensuring accurate representation of energy metrics in responses.
> Enhance job retrieval and pagination features

- folding/organic/api.py
- neurons/validator.py
- Implemented a new function to start the organic API in a separate process.
- Introduced a PipeOrganicValidator class to handle job communication between the API and the main process.
- Updated the Validator class to utilize the new process-based API, including handling pipe communication for job processing.
- Ensured proper termination of the organic API process when the validator stops.
> Add multiprocessing support for organic API

- folding/registries/evaluation_registry.py
The trajectory RMSD check would pass even if RMSDs were nan
> Update median RMSD check in SyntheticMDEvaluator to handle NaN values

- folding/registries/evaluation_registry.py
- folding/utils/constants.py
- folding/validators/protein.py
This is in response to some instabilities regarding the thresholds. Fair warning, this was done based on intuition, and no data science was done in the determination of these values. It could result in additional issues.
> decrease gradient threshold, reduce window size

- folding/base/validator.py
- folding/utils/uids.py
make sure validators don't get miner incentive, and remove some old code
> make sure validators are not getting miner scores
